# ============================================================================
#
# 默认生成的配置旨在突出 Zensical 提供的功能，
# 并作为你自己的项目起点。
#
# ============================================================================

[project]

# site_name 会显示在页面头部和浏览器窗口标题中
#
# 了解更多: https://zensical.org/docs/setup/basics/#site_name
site_name = "MyZensical"

# site_description 会包含在 HTML 头部中，
# 应该提供对站点内容有意义的描述，供搜索引擎使用。
#
# 了解更多: https://zensical.org/docs/setup/basics/#site_description
site_description = "这是一个使用 Zensical 构建的文档网站。"

# site_author 属性。此项会用于 HTML 的 head 元素。
#
# 了解更多: https://zensical.org/docs/setup/basics/#site_author
site_author = "PYPTsca"

# site_url 是你站点的规范 URL。构建在线文档时建议设置。
# 了解更多: https://zensical.org/docs/setup/basics/#site_url
site_url = "pyptscaZensical"

# 版权声明会显示在页面页脚中，并且可以包含 HTML 片段。
#
# 了解更多: https://zensical.org/docs/setup/basics/#copyright
copyright = """
Copyright &copy; 2026 The authors
"""

# Zensical 同时支持隐式导航和显式定义导航。
# 如果你决定不在这里定义导航，Zensical 会直接
# 从你的 "docs_dir" 目录结构推导导航结构。
# 下面的定义演示了如何使用 TOML 语法定义导航结构。
#
# 了解更多: https://zensical.org/docs/setup/navigation/
nav = [
  { "玩《魔法少女的魔女审判》艾玛有感" = "Emma.md" },
  { "Zensical完全使用教程" = "zensical-Tutorial.md" },
  { "Get started" = "index.md" },
  { "Markdown in 5min" = "markdown.md" },
]

# 通过 "extra_css" 选项，你可以添加自己的 CSS 样式，
# 以按需自定义你的 Zensical 项目。你可以添加任意数量的
# CSS 文件。
#
# 提供的路径应相对于 "docs_dir"。
#
# 了解更多: https://zensical.org/docs/customization/#additional-css
#
#extra_css = ["stylesheets/extra.css"]

# 通过 `extra_javascript` 选项，你可以向项目添加自定义 JavaScript，
# 以按需调整行为。
#
# 提供的路径应相对于 "docs_dir"。
#
# 了解更多: https://zensical.org/docs/customization/#additional-javascript
#extra_javascript = ["javascripts/extra.js"]

# ----------------------------------------------------------------------------
# 用于配置主题选项的部分
# ----------------------------------------------------------------------------
[project.theme]

# 将此项改为 "classic" 可使用传统的 Material for MkDocs 外观。
variant = "modern"

# Zensical 允许你覆盖特定区块、局部模板或整个模板，
# 也支持定义你自己的模板。要这样做，请取消注释下面的
# custom_dir 设置，并将其指向存放模板覆盖文件的目录。
#
# 了解更多:
# - https://zensical.org/docs/customization/#extending-the-theme
#
#custom_dir = "overrides"

# 通过 "favicon" 选项，你可以设置自己的图片作为图标，
# 浏览器会在标题栏或标签页中使用它。提供的路径
# 必须相对于 "docs_dir"。
#
# 了解更多:
# - https://zensical.org/docs/setup/logo-and-icons/#favicon
# - https://developer.mozilla.org/en-US/docs/Glossary/Favicon
#
#favicon = "images/favicon.png"

# Zensical 支持 60 多种语言。这意味着 Zensical 模板生成的
# 标签和工具提示都可以被翻译。
# "language" 选项允许你设置所用语言。该语言
# 也会在 HTML 头部中标记，以帮助提升可访问性，
# 并引导搜索引擎与翻译工具。
#
# 默认语言是 "en"（英语）。你也可以创建
# 多语言站点并配置语言选择器。详情请见文档。
#
# 了解更多:
# - https://zensical.org/docs/setup/language/
#
language = "zh"

# Zensical 提供了多个功能开关，可改变文档站点的行为。
features = [
  #"navigation.instant",          # 即时导航
  #"navigation.instant.prefetch", # 预加载
  #"navigation.tracking",         # 锚点跟踪
  #"navigation.tabs",             # 导航标签
  #"navigation.sections",         # 导航部分
  #"navigation.expand",           # 展开导航
  #"navigation.top",              # 返回顶部按钮
  #"navigation.footer",           # 页脚导航

  # Zensical 包含公告栏。该功能允许用户在阅读公告后
  # 将其关闭。
  # https://zensical.org/docs/setup/header/#announcement-bar
  "announce.dismiss",

  # 如果你已配置代码仓库并启用该功能，Zensical
  # 会为页面生成编辑按钮。适用于常见的
  # 代码托管服务。
  # https://zensical.org/docs/setup/repository/#content-actions
  "content.action.edit",

  # 如果你已配置代码仓库并启用该功能，Zensical
  # 会生成一个按钮，允许用户查看当前页面的
  # Markdown 源码。
  # https://zensical.org/docs/setup/repository/#content-actions
  #"content.action.view",

  # 代码注释功能允许你在代码块中添加带提示的图标，
  # 以解释关键位置。
  # https://zensical.org/docs/authoring/code-blocks/#code-annotations
  "content.code.annotate",

  # 该功能会在代码块中启用复制按钮，用户无需先选中内容
  # 即可复制到剪贴板。
  # https://zensical.org/docs/authoring/code-blocks/#code-copy-button
  "content.code.copy",

  # 代码块可包含一个按钮，允许用户选择行范围。
  # https://zensical.org/docs/authoring/code-blocks/#code-selection-button
  "content.code.select",

  # Zensical 可以将脚注渲染为行内提示，用户无需离开
  # 当前文档上下文即可阅读脚注。
  # https://zensical.org/docs/authoring/footnotes/#footnote-tooltips
  "content.footnote.tooltips",

  # 如果你有许多标题相同的内容标签页（例如 "Python"、
  # "JavaScript"、"Cobol"），该功能会让它们在用户
  # 切换其中一个时同步切换。
  # https://zensical.org/docs/authoring/content-tabs/#linked-content-tabs
  "content.tabs.link",

  # 启用此功能后，用户可以给链接添加工具提示，
  # 当鼠标悬停时会显示。
  # https://zensical.org/docs/authoring/tooltips/#improved-tooltips
  "content.tooltips",

  # 启用此功能后，用户滚动超过一定位置时，
  # Zensical 会自动隐藏页头的部分内容。
  # https://zensical.org/docs/setup/header/#automatic-hiding
  # "header.autohide",

  # 启用该功能后，导航侧边栏中的所有可折叠分组
  # 默认会展开。
  # https://zensical.org/docs/setup/navigation/#navigation-expansion
  # "navigation.expand",

  # 该功能会在页脚启用导航元素，允许用户跳转到
  # 上一页或下一页。
  # https://zensical.org/docs/setup/footer/#navigation
  "navigation.footer",

  # 启用分区索引页后，文档可以直接附加到分区，
  # 这对提供概览页特别有用。
  # https://zensical.org/docs/setup/navigation/#section-index-pages
  "navigation.indexes",

  # 启用即时导航后，所有内部链接点击都会被拦截，
  # 并通过 XHR 分发，无需整页刷新。
  # https://zensical.org/docs/setup/navigation/#instant-navigation
  "navigation.instant",

  # 开启即时预取后，用户悬停链接时站点就会开始预取页面。
  # 这会降低用户感知到的加载时间。
  # https://zensical.org/docs/setup/navigation/#instant-prefetching
  "navigation.instant.prefetch",

  # 为了在慢速网络下使用即时导航时提供更好的体验，
  # 可启用进度指示器。
  # https://zensical.org/docs/setup/navigation/#progress-indicator
  "navigation.instant.progress",

  # 启用导航路径后，会在每个页面标题上方渲染面包屑导航。
  # https://zensical.org/docs/setup/navigation/#navigation-path
  "navigation.path",

  # 启用裁剪后，渲染的 HTML 中仅包含可见导航项，
  # 可使构建后站点体积减少 33% 或更多。
  # https://zensical.org/docs/setup/navigation/#navigation-pruning
  #"navigation.prune",

  # 启用分区后，在宽度高于 1220px 的视口中，顶级分区会
  # 作为分组渲染在侧边栏；在移动端则保持原样。
  # https://zensical.org/docs/setup/navigation/#navigation-sections
  "navigation.sections",

  # 启用标签页后，在宽度高于 1220px 的视口中，顶级分区会
  # 渲染在页头下方的菜单层；在移动端则保持原样。
  # https://zensical.org/docs/setup/navigation/#navigation-tabs
  #"navigation.tabs",

  # 启用粘性标签页后，导航标签会固定在页头下方，
  # 向下滚动时也始终可见。
  # https://zensical.org/docs/setup/navigation/#sticky-navigation-tabs
  #"navigation.tabs.sticky",

  # 当用户向下滚动后再次向上滚动时，
  # 可以显示返回顶部按钮。
  # https://zensical.org/docs/setup/navigation/#back-to-top-button
  "navigation.top",

  # 启用锚点跟踪后，地址栏中的 URL 会自动更新为
  # 目录中高亮的当前活动锚点。
  # https://zensical.org/docs/setup/navigation/#anchor-tracking
  "navigation.tracking",

  # 启用搜索高亮后，用户点击搜索结果并进入页面时，
  # Zensical 会高亮所有匹配项。
  # https://zensical.org/docs/setup/search/#search-highlighting
  "search.highlight",

  "search.suggest", # 搜索建议

  # 启用目录锚点跟随后，侧边栏会自动滚动，
  # 使活动锚点始终可见。
  # https://zensical.org/docs/setup/navigation/#anchor-following
  # "toc.follow",

  # 启用目录导航集成后，目录会始终作为左侧
  # 导航栏的一部分渲染。
  # https://zensical.org/docs/setup/navigation/#navigation-integration
  #"toc.integrate",
]

# ----------------------------------------------------------------------------
# 你可以在 "theme" 子节中使用 "logo" 选项配置自定义 logo，
# 使其显示在页头。logo 必须是 "docs_dir" 中某个文件的相对路径，
# 例如要使用 `docs/assets/logo.png`，你可以这样设置：
# ----------------------------------------------------------------------------
#logo = "assets/logo.png"

# ----------------------------------------------------------------------------
# 如果你没有专门的项目 logo，可以使用 Zensical 自带图标集中的
# 内置图标。请注意，该设置位于不同的子节中，
# 并且上面的 logo 设置优先级高于图标设置。
#
# 了解更多:
# - https://zensical.org/docs/setup/logo-and-icons
# - https://github.com/zensical/ui/tree/master/dist/.icons
# ----------------------------------------------------------------------------
#[project.theme.icon]
#logo = "lucide/smile"

# ----------------------------------------------------------------------------
# 在 "font" 子节中你可以配置所使用的字体。默认情况下，字体
# 从 Google Fonts 加载，可在一组适当授权的字体中进行广泛选择。
# 你可以分别设置正文文本字体和代码块使用的等宽字体。
# ----------------------------------------------------------------------------
#[project.theme.font]
#text = "Inter"
#code = "Jetbrains Mono"

# ----------------------------------------------------------------------------
# 在 "palette" 子节中你可以配置配色方案相关选项。
# 你可以设置多个不同配色方案（例如启用深色模式），
# 供用户切换使用。每个配色方案都可进一步定制。
#
# 了解更多:
# - https://zensical.org/docs/setup/colors/
# ----------------------------------------------------------------------------

# 自动模式（跟随系统）
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle = { icon = "lucide/sun-moon", name = "关闭自动模式" }

# 日间模式
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "indigo"
accent = "indigo"
toggle = { icon = "lucide/sun", name = "切换至夜间模式" }

# 夜间模式
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "indigo"
accent = "indigo"
toggle = { icon = "lucide/moon", name = "切换至日间模式" }

# ----------------------------------------------------------------------------
# "extra" 区域包含杂项设置。
# ----------------------------------------------------------------------------
#[[project.extra.social]]
#icon = "fontawesome/brands/github"
#link = "https://github.com/user/repo"

# ----------------------------------------------------------------------------
# 在本节中，你可以配置渲染文档时使用的 Markdown 扩展。
# 默认启用了最常用的扩展，但你可以按需自定义此列表。
#
# 了解更多:
# - https://zensical.org/docs/setup/extensions/
# ----------------------------------------------------------------------------
[project.markdown_extensions.abbr]
[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.def_list]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.toc]
permalink = true
[project.markdown_extensions.pymdownx.arithmatex]
generic = true
[project.markdown_extensions.pymdownx.betterem]
[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.emoji]
emoji_generator = "zensical.extensions.emoji.to_svg"
emoji_index = "zensical.extensions.emoji.twemoji"
[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.keys]
[project.markdown_extensions.pymdownx.magiclink]
[project.markdown_extensions.pymdownx.mark]
[project.markdown_extensions.pymdownx.smartsymbols]
[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" },
]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
combine_header_slug = true
[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true
[project.markdown_extensions.pymdownx.tilde]
